### join mission
# @prompt mission_id Mission ID to Join


@menta = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjE1LCJleHAiOjE3NjcxNTY5NTksImlhdCI6MTc2NjU1MjE1OX0.wEkOI5V1u-p7mxT26bJ_65lXfqD-6AQuyI73iRAFJ4s

POST http://127.0.0.1:8000/api/crew/join/{{mission_id}}
Content-Type: application/json
Authorization: Bearer {{menta}}



### leave mission
# @prompt mission_id Mission ID to Leave
DELETE  http://127.0.0.1:8000/api/crew/leave/{{mission_id}}
Content-Type: application/json
Authorization: Bearer {{menta}}

